const assert = require("assert");
const p = require("../extension/api_host_policy.js");
assert.deepStrictEqual(p.parseHostAllowlist([]), []);
assert.deepStrictEqual(p.parseHostAllowlist(["B.example", "b.example"]), ["b.example"]);
for (const x of ["*.example.com", "http://example.com", "example.com:443", "example.com/path"]) assert.throws(() => p.parseHostAllowlist([x]));
assert.throws(() => p.resolveApiUrl("http://b.example", ["b.example"]));
assert.throws(() => p.resolveApiUrl("https://b.example:443", ["b.example"]));
assert.throws(() => p.resolveApiUrl("https://a.example", ["b.example"]));
assert.throws(() => p.resolveApiUrl("/backend-api/x", []), /API host allowlist is empty/);
const policy = p.createPolicy(["a.example", "b.example"]);
assert(policy.capture("https://b.example/login", "Bearer bravo"));
assert.strictEqual(policy.token("https://b.example/api"), "bravo");
assert.strictEqual(policy.token("https://a.example/api"), null);
policy.setHosts(["a.example", "chatgpt.com"]);
assert.strictEqual(policy.token("https://b.example/api"), null);
assert.strictEqual(policy.resolve("/backend-api/x"), "https://a.example/backend-api/x");
assert.strictEqual(policy.resolve("https://chatgpt.com/x"), "https://chatgpt.com/x");
assert.strictEqual(policy.capture("http://a.example/x", "Bearer nope"), false);
assert.strictEqual(policy.capture("not a URL", "Bearer nope"), false);
assert.strictEqual(policy.token("http://a.example/api"), null);
assert.strictEqual(policy.token("https://a.example:444/api"), null);
console.log("api host policy tests passed");
